# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('checkout', '0002_auto_20191017_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
