# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-14 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase',
        ),
    ]
