# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'video cards'), ('H', 'hard drives'), ('M', 'memory'), ('C', 'cpu'), ('CL', 'cooling'), ('MB', 'mother boards'), ('P', 'power supplies')], default='V', max_length=2),
            preserve_default=False,
        ),
    ]
