# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-11 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191104_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Video cards'), ('H', 'Hard drives'), ('M', 'Memory'), ('C', 'CPU'), ('CL', 'Cooling'), ('MB', 'Motherboards'), ('P', 'Prebuilt')], max_length=20),
        ),
    ]
